### ISSUE TITLE
How to test the app after building with --bundle-sksl-path?

### ISSUE THREAD

**Issue by kbokarius** [acoutts/flutter-engines-no-metal#1]
@acoutts thanks again for posting these. We just generated the flutter_01.sksl.json file and were able to build with `flutter build ios --bundle-sksl-path flutter_01.sksl.json`

However, what we're stuck on now is how to actually run that built binary. When we do a `flutter run` it looks like it rebuilds the binary and the jank is still there. After Googling around, according to https://github.com/flutter/flutter/issues/64626 the XCode -> Archive command uses the last `flutter build ios` configuration, so we're now trying that.

How do we do a `flutter run` without rebuilding or otherwise test the binary that includes the SKSL file in release mode on a physical device?

Also, can you please confirm that using Archive in XCode really will package in the SKSL file immediately after running `flutter build ios --bundle-sksl-path flutter_01.sksl.json`?

**Comment by acoutts** [comment]
Ah! The easiest thing to do is to build a signed IPA (using an AdHoc provisioning profile) and then install it through the Xcode devices settings by dragging/dropping it in. I've not used the Archive thing in Xcode yet, and instead just build an IPA using fastlane like I usually do for app store uploads, but use an AdHoc profile for sideloading.

**Comment by acoutts** [comment]
https://github.com/flutter/flutter/issues/53607#issuecomment-668364605 this is some good insight on how to do driver tests with the sksl cache.

**Comment by adeolaex** [comment]
Hey @acoutts 

Are there other ways to get the `No metal binary` on an IOS device ? 

If I'm not mistaken, using an AdHoc provisioning profile requires a developer account which I do not have access to.
I'm currently just exploring `flutter` and mobile dev at this point.

**Comment by acoutts** [comment]
Hm yeah you will need a provisioning profile to run it on a device I believe. These engines are for the profile/release engine, and you can only run debug builds without a developer account.

**Comment by adeolaex** [comment]
Interesting. Thanks for the swift response.

Although the Metal engines are also for profile/release/debug builds. Getting the final binary on an IOS device is usually as simple as running `flutter run --release` . 

Why isn't it as simple as that for the No metal engines ?

**Comment by acoutts** [comment]
I think as long as you replace the engine it should be the same thing.

**Comment by frankyvij** [comment]
Hi, the original question is not answered yet!

"Also, can you please confirm that using Archive in XCode really will package in the SKSL file immediately after running flutter build ios --bundle-sksl-path flutter_01.sksl.json"

Can anyone please confirm this?

**Comment by frankyvij** [comment]
Nevermind, found answers in this discussion: https://github.com/flutter/flutter/issues/64626
