### ISSUE TITLE
1.22.5 - blocked

### ISSUE THREAD

**Issue by acoutts** [acoutts/flutter-engines-no-metal#11]
Blocked on https://github.com/flutter/flutter/issues/72108

**Comment by vukhacbiet** [comment]
Hi @acoutts, Have any update?

**Comment by acoutts** [comment]
We’re still blocked until the fix mentioned in the linked issue makes it to stable.

**Comment by MarcoSoares11** [comment]
Hey @acoutts, are there any updates on the matter?

**Comment by pravinarr** [comment]
Hey @acoutts Is there any ETA for this one ?

**Comment by acoutts** [comment]
Just pinged in the blocked issue to see if it’s still an issue. Been super busy! Sorry for the delay everyone.

**Comment by acoutts** [comment]
As of https://github.com/flutter/flutter/issues/79298 metal now supports SkSL warmup. This repository will no longer be updated.
