### ISSUE TITLE
Flutter 1.22.6 (stable)

### ISSUE THREAD

**Issue by aleexbt** [acoutts/flutter-engines-no-metal#12]
Hello, would it be possible to release no metal for 1.22.6 version? Thanks.

**Comment by miguelpruivo** [comment]
Bumping this.

**Comment by skiny-n** [comment]
Pretty please 🥺 🙏

**Comment by acoutts** [comment]
As of https://github.com/flutter/flutter/issues/79298 metal now supports SkSL warmup. This repository will no longer be updated.
