### ISSUE TITLE
Flutter 2

### ISSUE THREAD

**Issue by britov** [acoutts/flutter-engines-no-metal#13]
Hello, would it be possible to release no metal for 2 version? Thanks.

**Comment by miguelpruivo** [comment]
@acoutts could you please provide us the steps to disable the Metal on a Flutter engine that could be easily done without requiring you to update every time a new version comes out? Thank you!

**Comment by ldasilva-net** [comment]
> @acoutts could you please provide us the steps to disable the Metal on a Flutter engine that could be easily done without requiring you to update every time a new version comes out? Thank you!

Take a look here https://github.com/flutter/flutter/issues/61045#issuecomment-661510986

**Comment by acoutts** [comment]
As of https://github.com/flutter/flutter/issues/79298 metal now supports SkSL warmup. This repository will no longer be updated.
