### ISSUE TITLE
OOM with no Metal framework?

### ISSUE THREAD

**Issue by hazzo** [acoutts/flutter-engines-no-metal#4]
Hi I was wondering if the engines are stable enough, because I'm seeing in some issues (for example this: [#60266](https://github.com/flutter/flutter/issues/60267#issuecomment-701518215)) stating that they have out of memory issues with this OpenGL flutter engines for iOS. Have you experienced any kind of OOM? Thanks for the engines! And it would be great too to have the last stable release: 1.22

Best regards!

**Comment by acoutts** [comment]
Hey there! I've not had any issues with OOM myself, though I haven't thoroughly tested with any intense screen animations. I'll get 1.22 up later this weekend / next week no problem.

**Comment by hazzo** [comment]
Thanks a lot for the quick response!!! Have a great weekend!

**Comment by acoutts** [comment]
Just add 1.22.0.

**Comment by hazzo** [comment]
Wow that was fast! Later today I'll test it. Thanks!
