### ISSUE TITLE
Flutter 1.22.2 (Stable/84f3d28)

### ISSUE THREAD

**Issue by jagandeepbrar** [acoutts/flutter-engines-no-metal#6]
Don't mean to be a bother, but would it be possible to also get a build of the latest stable release from today?

Version 1.22.2, ref 84f3d28.

**Comment by acoutts** [comment]
Completed with https://github.com/acoutts/flutter-engines-no-metal/commit/b9fb8192e153b49e3d9ceefea99725df063baadd
