### ISSUE TITLE
Request No Metal engines 1.22.4

### ISSUE THREAD

**Issue by wem2017** [acoutts/flutter-engines-no-metal#9]
Hi @acoutts 
Please update Request No Metal engines 1.22.4.
Thanks

**Comment by wem2017** [comment]
hello, have any update?

**Comment by vukhacbiet** [comment]
hope an update

**Comment by acoutts** [comment]
Compiling this now.

**Comment by acoutts** [comment]
Closed via https://github.com/acoutts/flutter-engines-no-metal/commit/dc658513f0675c209768e7f2232e44cba53db757
